# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20171117_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='RANDOM', max_length=128)),
                ('created', models.DateField(auto_now=True)),
                ('rank', models.PositiveIntegerField(blank=True, default=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(blank=True, default=100, on_delete=django.db.models.deletion.CASCADE, to='post.Section'),
        ),
    ]
