# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_profile',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='organization_profile',
            name='number_of_eployees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization_profile',
            name='organisation_image',
            field=models.ImageField(blank=True, upload_to='profilepic/'),
        ),
    ]
