# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171116_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization_profile',
            old_name='number_of_eployees',
            new_name='number_of_employees',
        ),
    ]
