# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171116_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization_profile',
            name='organisation_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
