# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 04:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20171116_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization_profile',
            name='organisation_name',
            field=models.CharField(default='something', max_length=128),
        ),
    ]
