# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='About_me',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
