# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_about_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='About_me',
            new_name='about_me',
        ),
    ]
