# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180128_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='keyskills',
        ),
    ]
