# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180203_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
