# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('highest_degree', models.CharField(choices=[('High School', 'HIGH SCHOOL'), ('undergrad', 'UNDERGRAD'), ('postgrad', 'POSTGRAD')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.DateTimeField()),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('cert_image', models.ImageField(blank=True, upload_to='cert_images/')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.DateTimeField()),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('organisation', models.CharField(blank=True, max_length=128)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Bio')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=128, null=True)),
                ('designation', models.CharField(blank=True, max_length=128, null=True)),
                ('worked_from', models.DateTimeField()),
                ('worked_till', models.DateTimeField()),
                ('current', models.BooleanField(default=False)),
                ('describe', models.TextField(blank=True)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Bio')),
            ],
        ),
    ]
