# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20171113_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certification',
        ),
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
